updates versioning script in order to always patch the module

diff --git a/bin/version/auto b/bin/version/auto
--- a/bin/version/auto
+++ b/bin/version/auto
@@ -1,22 +1,53 @@
-#!/usr/bin/env node
+#!/usr/bin/env bash
 
-console.log('> version:auto')
+set -e
+echo "> version:auto"
 
-// # ### running continuous integration build on node.js matrix
-// # git reset --hard origin/master
-// # npm run test
+git checkout npm 2>/dev/null || git checkout --orphan npm
+npm version patch -m "%s"
 
-// # ## in order to determine version bump entity
-// # git checkout head~2 -- test
+# git checkout head~2 -- test # todo: check if theres a previous commit
 
-// #  # run module api tests
-// # if [ -d test/module ] && {
+# if [ -d test/module ] && {
 
-// #   npm run test -- $(find test/module -type f -name \*.js)
-// #     # if this fails
-// #       npm version major -m "%s"
-// #       exit 0
+#   npm run verify:major && {
+#     npm version major -m "%s"
+#     npm reset --hard test
+#     exit 0
+#   }
 
-// #   npm run test -- $(find test -type f -name *.js -not -path test/module/\*)
+#   npm run verify:minor && {
+#     npm version minor -m "%s"
+#     npm reset --hard test
+#     exit 0
+#   }
+#     # if this fails
 
-// # }
+
+#   npm run test -- $(find test -type f -name *.js -not -path test/module/\*)
+# }
+
+
+
+
+
+
+
+# ### running continuous integration build on node.js matrix
+# git reset --hard origin/master
+# npm run test
+
+# ## in order to determine version bump entity
+# git checkout head~2 -- test
+
+#  # run module api tests
+# if [ -d test/module ] && {
+
+#   npm run test -- $(find test/module -type f -name \*.js)
+#     # if this fails
+#       npm version major -m "%s"
+#       exit 0
+
+#   npm run test -- $(find test -type f -name *.js -not -path test/module/\*)
+
+# }
